export const env = {
  TRELLO_API_BASE_URL: process.env.REACT_APP_TRELLO_API_BASE_URL,
  TRELLO_API_KEY: process.env.REACT_APP_TRELLO_API_KEY,
  TRELLO_SERVER_TOKEN: process.env.REACT_APP_TRELLO_SERVER_TOKEN
}
